### ISSUE TITLE
Enhancement : Use of undeclared type 'TimeInterval' 

### ISSUE THREAD

**Issue by Gabrail** [hathway/JSONRequest#24]
just add **import Foundation** for using **TimeInterval** 
in file **JSONRequestVerbs.swift**

**Comment by misterwell** [comment]
@Gabrail -- are you seeing this issue in the JSON xcode project? Or in an application using the project? In both scenarios on our side we're not seeing the error you're referring to, so I'm wondering what the difference is. Any ideas?

**Comment by Gabrail** [comment]
i saw this error when using with project i have , it give me error when using **TimeInterval**

**Comment by nbeadman** [comment]
Closed as 5 years old
