### ISSUE TITLE
Could you update the project to the latest Xcode and Swift version.

### ISSUE THREAD

**Issue by yourconnery** [hathway/JSONRequest#8]
This project is awesome and easy to use, but it is not possible to build in the latest Xcode. Could you update the project to the latest Xcode and Swift version. Thanks.

**Comment by misterwell** [comment]
@yourconnery -- Sorry for the delayed response, but v0.5.0 that I just released has been updated for the latest version of Xcode & Swift. Let me know if you run into any issues using it!
